// Candidate map: when plan is called, run one offline walk over the question (entry graph picks pages →
// pick a seed within each page → affinity-guided walk), and hand the candidate file list to the agent as
// an opening map — the agent's 8-call budget shifts from "blindly hunting for a path" to "verify and dig in".
// Rationale: metrics §2 measured the walker finding 85/144 answer files vs the agent seeing only 46/144 on its own.
// The index is already in memory: sub-second, zero LLM, zero network. Set ACA_ENTRY_MAP=0 to disable.
import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';
import { GLOBAL_INDEX } from '../../indexer/state.js';
import { relPath, isTestPath } from './common.js';
import { questionTokens, scoreString } from './walker/affinity.js';
import { informativeTokens, selectPages, resolveWikiFiles, selectSeedForPage } from './walker/entry.js';
import { buildDirectedAdjacency, walkFromSeed, type WalkCtx } from './walker/walk.js';
import type { WikiMap } from '../../wikimap/schema.js';
import { cosine, embedText } from './embeddings.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const WIKI_MAP_PATH = path.resolve(__dirname, '..', '..', '..', 'data', 'wiki-map.json');
const SUMMARIES_PATH = path.resolve(__dirname, '..', '..', '..', 'data', 'summaries', 'file-summaries.json');
const VECTORS_PATH = path.resolve(__dirname, '..', '..', '..', 'data', 'summaries', 'summary-vectors.json');
const MAX_CANDIDATES = 25;

// One-line file summaries (generated by summaries:gen, hash-cached) — ranking semantic term + candidate map annotations. null when the file is missing (runs as before).
let summariesCache: Record<string, { hash: string; ranking_line: string }> | null | undefined;
export function loadSummaries(): Record<string, { hash: string; ranking_line: string }> | null {
    if (summariesCache !== undefined) return summariesCache;
    try { summariesCache = JSON.parse(fs.readFileSync(SUMMARIES_PATH, 'utf-8')); }
    catch { summariesCache = null; }
    return summariesCache;
}

// Lazy singleton: wiki-map + directed adjacency + file→symbol reverse lookup are all built once (the index is immutable per process).
let cached: {
    wikiMap: WikiMap | null;
    ctx: WalkCtx;
    allFiles: string[];
    symbolsOfFile: (realPath: string) => string[];
} | null = null;

function deps() {
    if (cached) return cached;
    let wikiMap: WikiMap | null = null;
    try { wikiMap = JSON.parse(fs.readFileSync(WIKI_MAP_PATH, 'utf-8')); }
    catch { console.error('[entry-map] data/wiki-map.json missing/unreadable — candidate map disabled (rebuild: npm run wiki:map)'); }
    const byFile = new Map<string, string[]>();
    for (const [sym, paths] of GLOBAL_INDEX.symbols) {
        for (const p of paths) {
            let arr = byFile.get(p); if (!arr) { arr = []; byFile.set(p, arr); } arr.push(sym);
        }
    }
    for (const arr of byFile.values()) arr.sort();
    const symbolsOfFile = (f: string) => byFile.get(f) ?? [];
    const allFiles = [...GLOBAL_INDEX.allFiles];
    const realByRel = new Map(allFiles.map(f => [relPath(f), f]));
    const ctx: WalkCtx = {
        adj: buildDirectedAdjacency(GLOBAL_INDEX.callGraph),
        filesOf: (sym) => [...(GLOBAL_INDEX.symbols.get(sym) ?? [])].sort().map(relPath),
        symbolsOfFile: (relF) => { const real = realByRel.get(relF); return real ? symbolsOfFile(real) : []; },
    };
    cached = { wikiMap, ctx, allFiles, symbolsOfFile };
    return cached;
}

interface Analysis {
    tokens: string[];
    chosenPages: import('../../wikimap/schema.js').WikiPage[];
    seeds: string[];
    ranked: string[];
    pageOf: (f: string) => string;
}

const RRF_K = 60;

/**
 * Candidate hybrid ranking (the single implementation shared by production and measurement): graph proximity dominates (doubled) + lexical assist.
 * Rationale for the 2:1 weighting (user judgment, same philosophy as expand.ts's 2.0×proximity+1.5×lex): answer files form
 * a logical chain wired around the seed, so graph distance is the primary signal; pure lexical ranking buries core files like
 * apn.ts/fcm.ts — "no name signal, only structural signal" — deep in the large graph (2026-07-08 precision measurement: the top 25
 * averaged only 0.9 answer-relevant files). The earlier the discovery round, the closer to the seed: primary term 2/(1+round)
 * (seed's own file=2.0, round 1=1.0, round 2=0.67…), with the lexical score (0..~0.9) as an assist term. Test files never become candidates.
 * When sem is provided, RRF-fuse the fuzzy ranking with the semantic cosine ranking (K=60).
 */
export function rankCandidates(
    items: Array<{ f: string; round: number }>, tokens: string[],
    summaries?: Record<string, { ranking_line: string }> | null,
    sem?: { queryVec: Float32Array; vecOf: (rel: string) => Float32Array | null } | null,
): string[] {
    const live = items.filter(x => !isTestPath(x.f));
    // Signal 1: fuzzy (existing score, graph proximity + literal name)
    const fuzzyScore = (x: { f: string; round: number }) => {
        const nameFace = scoreString(tokens, x.f);
        const sumFace = summaries?.[x.f] ? scoreString(tokens, summaries[x.f].ranking_line) : 0;
        return 2 / (1 + x.round) + Math.max(nameFace, sumFace);
    };
    const fuzzyRanked = [...live].sort((a, b) => fuzzyScore(b) - fuzzyScore(a) || a.f.localeCompare(b.f));
    // No semantic input → fall back to fuzzy-only (backward compatible)
    if (!sem) return fuzzyRanked.map(x => x.f);
    // Signal 2: semantic cosine (files without a vector rank last)
    const semRanked = [...live].sort((a, b) => {
        const va = sem.vecOf(a.f), vb = sem.vecOf(b.f);
        const sa = va ? cosine(sem.queryVec, va) : -Infinity;
        const sb = vb ? cosine(sem.queryVec, vb) : -Infinity;
        return sb - sa || a.f.localeCompare(b.f);
    });
    // RRF fusion
    const fr = new Map<string, number>(); fuzzyRanked.forEach((x, i) => fr.set(x.f, i + 1));
    const sr = new Map<string, number>(); semRanked.forEach((x, i) => sr.set(x.f, i + 1));
    return [...live]
        .map(x => ({ f: x.f, s: 1 / (RRF_K + fr.get(x.f)!) + 1 / (RRF_K + sr.get(x.f)!) }))
        .sort((a, b) => b.s - a.s || a.f.localeCompare(b.f))
        .map(x => x.f);
}

// Lazily-loaded vector table
let vecCache: Map<string, Float32Array> | null | undefined;
export function loadVectors(): Map<string, Float32Array> | null {
    if (vecCache !== undefined) return vecCache;
    try {
        const raw: Record<string, { vec: string }> = JSON.parse(fs.readFileSync(VECTORS_PATH, 'utf-8'));
        const m = new Map<string, Float32Array>();
        for (const [rel, e] of Object.entries(raw)) {
            const buf = Buffer.from(e.vec, 'base64');
            m.set(rel, new Float32Array(buf.buffer, buf.byteOffset, buf.byteLength / 4));
        }
        vecCache = m;
    } catch { vecCache = null; }
    return vecCache;
}

// query vector cache (embed each question string only once)
const qvecCache = new Map<string, Float32Array>();
async function cachedQueryVec(question: string): Promise<Float32Array> {
    let v = qvecCache.get(question);
    if (!v) { v = await embedText(question); qvecCache.set(question, v); }
    return v;
}
/** Assemble the RRF semantic parameters; returns null when the vector table is missing (rankCandidates automatically falls back to fuzzy). */
async function semFor(question: string): Promise<{ queryVec: Float32Array; vecOf: (f: string) => Float32Array | null } | null> {
    const vecs = loadVectors();
    if (!vecs) return null;
    return { queryVec: await cachedQueryVec(question), vecOf: (f) => vecs.get(f) ?? null };
}

// Shared analysis core: pick pages → pick a seed per page → walk → rank candidates. Shared by candidateMap and offlineWikiAnswer.
async function analyze(question: string): Promise<Analysis | null> {
    if (process.env.ACA_ENTRY_MAP === '0' || !question) return null;
    const { wikiMap, ctx, allFiles, symbolsOfFile } = deps();
    if (!wikiMap || GLOBAL_INDEX.symbols.size === 0) return null;

    const { kept: tokens } = informativeTokens(questionTokens(question), wikiMap);
    const pageStep = selectPages(tokens, wikiMap);
    if (!pageStep) return null;

    const chosenPages = pageStep.chosen
        .map(name => wikiMap.pages.find(p => p.page === name))
        .filter((p): p is NonNullable<typeof p> => !!p);
    const seeds: string[] = [];
    for (const page of chosenPages) {
        const { resolved } = resolveWikiFiles(Object.keys(page.source_files), allFiles);
        const step = selectSeedForPage(tokens, page, resolved, symbolsOfFile);
        if (step.chosen) seeds.push(step.chosen);
    }
    if (seeds.length === 0) return null;

    // Record the round in which each file was first discovered (the seed's own file = round 0) — the graph-proximity signal for ranking
    const firstRound = new Map<string, number>();
    for (const seed of new Set(seeds)) {
        for (const f of ctx.filesOf(seed)) if (!firstRound.has(f)) firstRound.set(f, 0);
        for (const w of walkFromSeed(seed, ctx, tokens)) {
            for (const f of (w.result?.newFiles ?? [])) {
                if (!firstRound.has(f) || firstRound.get(f)! > w.round) firstRound.set(f, w.round);
            }
        }
    }
    const ranked = rankCandidates([...firstRound].map(([f, round]) => ({ f, round })), tokens, loadSummaries(), await semFor(question))
        .slice(0, MAX_CANDIDATES);
    if (ranked.length === 0) return null;

    const pageOf = (f: string) => {
        const k = Object.keys(wikiMap.file_to_pages).find(w => f.endsWith(w) || f === w);
        return k ? `  (page: ${wikiMap.file_to_pages[k][0]})` : '';
    };
    return { tokens, chosenPages, seeds, ranked, pageOf };
}

function candidateLines(a: Analysis): string[] {
    return [
        `Entry pages: ${a.chosenPages.map(p => p.page).join(' / ')}`,
        `Suggested seed symbols: ${[...new Set(a.seeds)].join(', ')}`,
        `Candidate files, ranked by graph proximity to the seeds + relevance (top ${a.ranked.length}):`,
        ...a.ranked.map(f => {
            const sum = loadSummaries()?.[f]?.ranking_line;
            return `- ${f}${a.pageOf(f)}${sum ? ` — ${sum}` : ''}`;
        }),
        `⚠️ These are CANDIDATES, not the answer: you MUST confirm every file you cite via search/graph/details — citing unverified paths is an error. Files not listed here may still matter.`,
    ];
}

/** Lightweight "question→matched pages" matching only (used by the wiki tool's prose retrieval); touches neither prose nor walk results. */
export async function matchPages(question: string): Promise<{ pages: string[]; tokens: string[] } | null> {
    const a = await analyze(question);
    return a ? { pages: a.chosenPages.map(p => p.page), tokens: a.tokens } : null;
}

/** Run an offline walk over the question and return the candidate-map text attached to the agent; returns null when disabled / no entry graph / no hit (plan runs as before). */
export async function candidateMap(question: string): Promise<string | null> {
    const a = await analyze(question);
    if (!a) return null;
    return [
        `\n## 📍 Candidate map (derived offline from the architecture wiki-map + a graph walk — NOT LLM-generated)`,
        ...candidateLines(a),
    ].join('\n');
}

// mermaid edge rendering: node id → label (truncated), only rendering edges where both endpoint labels exist
const trimLabel = (s: string) => (s.length > 48 ? s.slice(0, 45) + '…' : s);

/** Offline wiki answer (based on the self-generated architecture wiki): entry-page structure (sections + relation edges) + candidate files. Structure only, no prose. */
export async function offlineWikiAnswer(question: string): Promise<string | null> {
    const a = await analyze(question);
    if (!a) return null;
    const L: string[] = [
        `## 🗺 Architecture map (offline, derived from the self-generated architecture wiki — structure only, no prose)`,
    ];
    for (const p of a.chosenPages) {
        L.push(`\n### ${p.page}`);
        if (p.sections.length) L.push(`Sections: ${p.sections.join(' · ')}`);
    }
    // Rank relation edges globally by relevance to the question and take the top — don't spend budget page by page,
    // to prevent one noisy page (e.g. CI/CD git pipeline edges) from eating the budget and crowding out the edges of
    // truly relevant pages (2026-07-08 smoke-test evidence).
    const scoredEdges: Array<{ line: string; s: number }> = [];
    for (const p of a.chosenPages) {
        for (const d of p.diagrams) {
            for (const e of d.edges) {
                const from = d.nodes[e[0]], to = d.nodes[e[1]];
                if (!from || !to) continue;
                const s = Math.max(scoreString(a.tokens, from), scoreString(a.tokens, to));
                scoredEdges.push({ line: `- ${trimLabel(from)} → ${trimLabel(to)}${e[2] ? `  (${e[2]})` : ''}  [${p.page}]`, s });
            }
        }
    }
    const topEdges = scoredEdges.sort((x, y) => y.s - x.s || x.line.localeCompare(y.line)).slice(0, 16).filter(e => e.s > 0);
    if (topEdges.length) {
        L.push(`\nComponent relations most relevant to the question:`);
        L.push(...topEdges.map(e => e.line));
    }
    L.push('');
    L.push(...candidateLines(a));
    return L.join('\n');
}
